### ISSUE TITLE
Whether there can be parameters to control the expansion prohibition

### ISSUE THREAD

**Issue by sdjwj1118** [congthanhng/Expansion-Tile-Group#22]
Whether there can be parameters to control the expansion prohibition Example：isEnableExpanded : false

**Comment by congthanhng** [comment]
Hi @sdjwj1118, Could you give me more detail about your scenario?
Example: If the initial state is `collapse`, and you prohibit `expand`, the widget will never be expanded. It will look exactly like ListTile.

**Comment by sdjwj1118** [comment]
Hey, because I need to implement a function, for example, the list can only be expanded after the network request. I need to directly prohibit expanding the list after the request. Can I add a parameter to control? Thank you

**Comment by congthanhng** [comment]
Thanks @sdjwj1118, i think it is good feature. Let me improve this. It will be gained in next version.

**Comment by sdjwj1118** [comment]
OK, thank you. I hope to use the new version as soon as possible. Thank you for your adoption

**Comment by congthanhng** [comment]
Hi @sdjwj1118, new version 1.1.7 has came, please test it with your scenario.
Thanks again for your contributing.

**Comment by sdjwj1118** [comment]
嗨。我已经在尝试使用1.1.7版本。新增的isEnableExpanded参数确实可以实现我需要的功能，但是我发现一个问题，我在使用Getx的时候，定义了一个参数值为isOpenPowerSupplySystem，使用Obx包裹ExpansionTileGroup，在网络请求后修改isOpenPowerSupplySystem为true，但是并不能展开列表
![image](https://user-images.githubusercontent.com/33438073/211298747-6ab8675d-7cea-4816-8f4f-73b52bcd2fd2.png)
![image](https://user-images.githubusercontent.com/33438073/211298791-b4be3f0f-8089-462c-b688-71eee60d3c38.png)

**Comment by congthanhng** [comment]
Let me explain why it happened: when you wrap items inside `ExpansionTileGroup`, all children are created with a `key`, So when you rebuild the widget, the widget will be not changed.
Let me improve the `ExpansionTileGroup` in next version @sdjwj1118

**Comment by sdjwj1118** [comment]
![image](https://user-images.githubusercontent.com/33438073/211299785-ed1613bc-9412-4a3b-9c56-5780e9fc1843.png)
I see in your code that isEnableExpanded is initialized in the initState method. Will you not call initState again when refreshing the interface?

**Comment by sdjwj1118** [comment]
Okay, look forward to the next version

**Comment by congthanhng** [comment]
Hi @sdjwj1118 , new version 1.1.8 has came. Please test it again and send me your feedback. 
Thanks again for your contributing.

**Comment by sdjwj1118** [comment]
![image](https://user-images.githubusercontent.com/33438073/211305539-c10028ed-965d-461e-b70b-29610c12434e.png)
What happened?

**Comment by congthanhng** [comment]
You can try pub get again @sdjwj1118

**Comment by sdjwj1118** [comment]
OK, I have another question. Is there a default spacing between the title and children of the ExpansionTileItem?

**Comment by sdjwj1118** [comment]
Still not. I think it may take about 10 minutes

**Comment by congthanhng** [comment]
> OK, I have another question. Is there a default spacing between the title and children of the ExpansionTileItem?

You can use `tilePadding` parameter @sdjwj1118

**Comment by congthanhng** [comment]
> Still not. I think it may take about 10 minutes

Could you please give me your feedback @sdjwj1118 ?

**Comment by sdjwj1118** [comment]
Still can't download the new version

**Comment by congthanhng** [comment]
Please try with 1.1.9 @sdjwj1118

**Comment by sdjwj1118** [comment]
I think this version is ok

**Comment by sdjwj1118** [comment]
thank u very much

**Comment by congthanhng** [comment]
If you like my package, please feel free give me a star for this repo OR a like in pub.dev. If you have any idea need me implement, please create a new issues for this OR create a new PR. Thanks a lot. Have a good day!
