### ISSUE TITLE
Error with GlobalKey

### ISSUE THREAD

**Issue by eg-97kr** [congthanhng/Expansion-Tile-Group#26]
Hello! 
After update 1.2.0, it swears that the global key is called twice, although the GlobalKey is not required in the extension_tile_group, and in all applications the GlobalKey is used only once, in a widget not associated with the extension_tile_group

A GlobalKey was used multiple times inside one widget's child list.
The relevant error-causing widget was
ExpansionTileGroup

Thanks

**Comment by congthanhng** [comment]
Hi @eg-97kr , thanks your issues. Let me check it, i'll response you soon.

**Comment by congthanhng** [comment]
Could you please show me your code?

**Comment by eg-97kr** [comment]
This is how I call extension_tile_group.
![Снимок экрана 2023-02-10 193050](https://user-images.githubusercontent.com/100346247/218157718-4ba5a8c7-93ce-4558-af0c-ad3108b59bbb.png)

The parameters in all ExpansionTileBorderItem are the same, only the content of 'children' changes.

The only place where the GlobalKey is used is in the file with the qr-code scanner, which is not related to the file that uses the extension_tile_group
![Снимок экрана 2023-02-10 193626](https://user-images.githubusercontent.com/100346247/218158922-81e821d6-62c6-4485-88c5-175a2e6dbb97.png)

**Comment by congthanhng** [comment]
Hi @eg-97kr , I don't think the `extension_tile_group` is causing the error because it is not related to the `qr_code scanner`.
Could you please show me the error console log of it?

**Comment by eg-97kr** [comment]
Hi @congthanhng, ure, no problem. Here is the console error log
![Снимок экрана 2023-02-12 163330](https://user-images.githubusercontent.com/100346247/218317267-22ee9ca5-bf4b-4b44-a86e-c9f27def2d8f.png)

When I took a screenshot, I noticed that another error pops up, "type 'Null' is not a subtype of type 'bool'". Before that, I didn’t pay attention, because the GlobalKey error immediately popped up on the emulator screen, and I was looking for it in the console, apparently that’s why I didn’t notice the Null error earlier

Here is what it looks like in the emulator

![Снимок экрана 2023-02-12 163835](https://user-images.githubusercontent.com/100346247/218317527-9d6c3053-520e-4af8-9435-9365711629b7.png)

**Comment by congthanhng** [comment]
Hi @eg-97kr , thanks for your feedback. Let me check it immediately and response you soon.

**Comment by congthanhng** [comment]
Hi @eg-97kr , Thank you for your contribution, i've published new version 1.2.1 to fix the issue `type "Null" is not a subtype of type bool`, please check it, look forward to hear from you soon.

**Comment by eg-97kr** [comment]
Hi @congthanhng. The widget works like a clock. Thank you very much ))
