### ISSUE TITLE
Add mouse cursor support on Web

### ISSUE THREAD

**Issue by eggp** [congthanhng/Expansion-Tile-Group#33]
Hello!

Please add hover clickable cursor support to ExpansionTileItem.

Thanks

**Comment by congthanhng** [comment]
Hi @eggp, thank for using my package. About your concern, I will consider and improve it when it impossible. I will inform you when i done.

**Comment by eggp** [comment]
@congthanhng Thanks in advance

**Comment by congthanhng** [comment]
Hi @eggp , The `ExpansionTileItem` is extended from `ExpansionTile` of Flutter, so it has already the clickable to expand and collapse.
Can you explain me more the detail about your case?

**Comment by eggp** [comment]
Hi @congthanhng,

I'm trying in 1.2.2 and it doesn't show the mouse click cursor in the examples. And I try it in 1.2.3, and only a cursor appears for one element:

![image](https://github.com/congthanhng/Expansion-Tile-Group/assets/1015211/16d87b20-d95c-49d0-a75c-fe6d061d7fe9)

Summary:
In 1.2.3 when `isDefaultVerticalPadding: false`  only then will the cursor appear
