### ISSUE TITLE
Latest version violates SemVer!

### ISSUE THREAD

**Issue by dustin-graham** [congthanhng/Expansion-Tile-Group#47]
Your latest release 1.3.0 has several breaking changes from 1.2.8. This release does not follow semver and causes build failures in apps that depend on your package. See SemVer documentation summary: https://semver.org/#summary

1.3.0 is a minor upgrade which should be: "MINOR version when you add functionality in a backward compatible manner"

Your change was not backward compatible and therefore should have been a major version change: 2.0.0. Please be more careful in future releases.

**Comment by congthanhng** [comment]
hi @dustin-graham thanks for suggestion. I will notice it in next work.
