### ISSUE TITLE
How the group features can be used in ListView.builder

### ISSUE THREAD

**Issue by codercengiz** [congthanhng/Expansion-Tile-Group#48]
I need to use `ExpansionTileGroup` for the list items, but it wants `ExpansionTileItem` childeren

**Comment by congthanhng** [comment]
hi @codercengiz, what usecase do you want to handle? The core concept of `group` feature is the `ExpansionTileGroup` always need `ExpansionTileItem` to generate keys. With these keys `ExpansionTileGroup` can easily handle the behaviors of `ExpansionTileItem`s.

**Comment by codercengiz** [comment]
I have a list that can contain many items, each with an expansion feature. If the user clicks on any item, it should expand. If there's another item already expanded, it should collapse. 
However I need to use list.builder.

**Comment by congthanhng** [comment]
Currently, this package does NOT support it yet.
I will add it in the future and inform you when it is ready. 
Thanks for contributing!

**Comment by congthanhng** [comment]
hi @codercengiz, a new version is released with supporting your case.
Please checkout the [docs](https://pub.dev/documentation/expansion_tile_group/latest/topics/Group%20features-topic.html) with `Option 2` section. Thanks and waiting your good feedback!

**Comment by codercengiz** [comment]
hi @congthanhng 
First of all, thank you very much for the quick solution.  
I had issues with just two cases, but I worked around them. However, I believe a cleaner method would be better.

1. Case:  
When I sort the list, the previously expanded item should stay expanded in whichever position it has moved to in the list.

I solved it by using `onItemChanged`:

```dart
expansionGroupController.onItemChanged(
        sortedEloboxes.indexWhere(
          (element) => element.key == state.expandedEloboxSerialNumber,
        ),
        true,
      );
```

2. Case:  
If the length of the list changes, especially when an item is deleted, I get a range error:  
`RangeError (length): Invalid value: Not in inclusive range 0..2: -1`

**Comment by congthanhng** [comment]
Hi @codercengiz,  your cases are so complicated. Please show your code, i will try to support you to find the solutions.

**Comment by congthanhng** [comment]
hi @codercengiz , i think this package is out of scope with your second case. You should re-init the controller and using UniqueKey for parent widget that wrapped all items of group. So that, whenever you change the list, it will be re-created to the new one.
Thanks for your feedback and provide me some useful cases. Hope my answer will find you well!
