### ISSUE TITLE
Remove top and bottom padding of title in ExpansionTileCard

### ISSUE THREAD

**Issue by tashda** [congthanhng/Expansion-Tile-Group#49]
Really love this package and am using it in my app.
However I have been trying to set the height/padding of the title, as the current height is a bit too much for my use case.

When trying to set the size of the Widget in the title, it doesn't affect the height of the title Card, but only the content inside it.

Is there a way to already achieve this or is this a feature request?

Kind of like #32 but for ExpansionTileCard instead of ExpansionTileItem

**Comment by congthanhng** [comment]
Hi @tashda , Thank you for choosing my package. 
Would you mind providing me your screenshot or the design? I will help you find the solution. Thanks

**Comment by tashda** [comment]
Thanks a lot for getting back to me.

I am using the ExpansionTileCard in a SliverList, where it is returned in the a ListTile in the itemBuilder.
![image](https://github.com/user-attachments/assets/5bb31584-c285-4e8f-844a-bb3e715e5cf9)

What I am trying to achieve is to remove the padding of the title in ExpansionTitleCard, as it is taking up a bit too much space for my liking.

**Comment by congthanhng** [comment]
Hi @tashda , did you try to add 'isDefaultVerticalPadding = false' to your ExpansionTileCard?

**Comment by tashda** [comment]
> Hi @tashda , did you try to add 'isDefaultVerticalPadding = false' to your ExpansionTileCard?

Thanks for your answer. This was of course the solution and I am now able to use the titlePadding of the ExpansionTileCard.

Now I just need how to make the padding of the ExpansionTileCard be the same whenever it is expanded or not.
Expanded
![image](https://github.com/user-attachments/assets/4dddda4b-e246-4e76-9f36-ea36db30f78e)

Collapsed
![image](https://github.com/user-attachments/assets/2a9839b2-d687-4d37-8def-65dc4976f761)


But I will try to figure this one out!
Thanks a million!
